name: sonar # ワークフロー名を決定

on:
    push: # プッシュ(マージ)が発生したときにトリガー
        branches:
            - main

jobs:
    sonarqube:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
          with:
              fetch-depth: 0
        - name: SonarQube Scan
          uses: sonarsource/sonarqube-scan-action@master
          env:
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
